# ----
# Site

title: CloudCannon
description: CloudCannon has everything you need to build, host and update Jekyll websites.
url: https://cloudcannon.com
disqus_shortname: cloudcannon
theme: jekyll-theme-cloudcannon
baseurl:

twitter:
  username: cloudcannon
  card: summary

active_sibling: Home
main_url: ""
google_analytics_key: "UA-37472773-1"
google_site_verification: GkBrJRSQqF43wQVGLUeUJFTPBldtIXGCw9toqvS2o_o
permalink: pretty
timezone: Pacific/Auckland
collections:
  case_studies:
    output: false
    permalink: /case-studies/:name/
  features:
    title: Features
    output: true
    permalink: /features/:name/
    _hide_content: true
  posts:
    _image_size: cover
  offices:
    output: false
    _hide_content: true
  staff_members:
    output: false
    _hide_content: true
defaults:
  - scope:
      path: ""
    values:
      header_class: "short"
  - scope:
      path: ""
      type: pages
    values:
      search_result_highlighting_selector: body
  - scope:
      path: ""
      type: "features"
    values:
      layout: "feature"
      search_result_highlighting_selector: body
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      search_result_highlighting_selector: div.post
      _options:
        content:
          uploads_dir: "images/blog/:title"
          format: p h2 h3 h4 h5 h6
          link: true
          removeformat: true
          bold: true
          italic: true
          image: true
          numberedlist: true
          bulletedlist: true
          code: true
          table: true
          embed: true
          styles: "src/css/editor.css"
        image:
          upload_dir: "images/blog/:title"

plugins:
  - jekyll-autoprefixer
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-data

# ----------
# SEO plugin

lang: en_NZ
logo: /siteicon.png
twitter:
  username: CloudCannon
facebook:
  publisher: https://www.facebook.com/CloudCannon
social:
  name: CloudCannon
  links:
    - https://twitter.com/CloudCannon
    - https://www.facebook.com/CloudCannon
    - https://plus.google.com/+CloudCannon
    - https://www.youtube.com/c/CloudCannon
    - https://github.com/CloudCannon

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json

recaptcha:
  sitekey: 6Lfng1EUAAAAAIqcLgzGcjRjVHR46BbyqZNgU2Xd

_comments: 
  tagline: "Social: used as part of the title tag of the home page like 'title | tagline'"
  description: "Social:  A longer description used for the description meta tag"
  image: "Social: URL to an image associated with the page (ideally 1200x630 and Less than 1MB)"
  title: "Social: The title of the page"

_options:
  content:
    format: p h2 h3 h4 h5 h6
    link: true
    removeformat: true
    bold: true
    italic: true
    image: true
    numberedlist: true
    bulletedlist: true
    code: true
    table: true
    styles: "css/editor.css"

plan_options:
  - 'True'
  - 'False'
  - 'Free'
  - 'Custom'
  - 'Basic'
  - 'Advanced'
  - 'Priority'
  - 'Yes*'
  - '$25/month'
  - '$75/month'
  - '$25/user/month'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
image_position:
  - 'Left'
  - 'Right'