# ----
# Site

title: CloudCannon
description: CloudCannon has everything you need to build, host and update Jekyll websites.
url: https://cloudcannon.com
disqus_shortname: cloudcannon
theme: jekyll-theme-cloudcannon
baseurl:

active_sibling: Home
main_url: ""
google_analytics_key: "UA-37472773-1"
google_site_verification: GkBrJRSQqF43wQVGLUeUJFTPBldtIXGCw9toqvS2o_o
permalink: pretty
timezone: Pacific/Auckland
collections:
  case_studies:
    output: false
    permalink: /case-studies/:name/
  features:
    title: Features
    output: true
    permalink: /features/:name/
    _hide_content: true
  posts:
    _image_size: cover
  offices:
    output: false
    _hide_content: true
  staff_members:
    output: false
    _hide_content: true
defaults:
  - scope:
      path: ""
    values:
      header_class: "short"
  - scope:
      path: ""
      type: pages
    values:
      search_result_highlighting_selector: body
  - scope:
      path: ""
      type: "features"
    values:
      layout: "feature"
      search_result_highlighting_selector: body
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      search_result_highlighting_selector: div.post
      _options:
        content:
          uploads_dir: "images/blog/:title"
          format: p h2 h3 h4 h5 h6
          link: true
          removeformat: true
          bold: true
          italic: true
          image: true
          numberedlist: true
          bulletedlist: true
          code: true
          table: true
          embed: true
          styles: "src/css/editor.css"
        image:
          upload_dir: "images/blog/:title"

plugins:
  - jekyll-autoprefixer
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-data

# ----------
# SEO plugin

lang: en_NZ
logo: /siteicon.png
twitter:
  username: CloudCannon
facebook:
  publisher: https://www.facebook.com/CloudCannon
social:
  name: CloudCannon
  links:
    - https://twitter.com/CloudCannon
    - https://www.facebook.com/CloudCannon
    - https://plus.google.com/+CloudCannon
    - https://www.youtube.com/c/CloudCannon
    - https://github.com/CloudCannon

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json

recaptcha:
  sitekey: 6Lfng1EUAAAAAIqcLgzGcjRjVHR46BbyqZNgU2Xd

_options:
  content:
    format: p h2 h3 h4 h5 h6
    link: true
    removeformat: true
    bold: true
    italic: true
    image: true
    numberedlist: true
    bulletedlist: true
    code: true
    table: true
    styles: "css/editor.css"

plan_options:
  - 'True'
  - 'False'
  - 'Free'
  - 'Custom'
  - 'Basic'
  - 'Advanced'
  - 'Priority'
  - 'Yes*'
  - '$25/month'
  - '$75/month'
  - '$25/user/month'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
image_position:
  - 'Left'
  - 'Right'

_array_structures:
  page_sections:
    - label: Page Section
      icon: view_agenda
      value:
        section_heading:
        components:
  components:
    - label: Content Block
      icon: subject
      value:
        _component_type: Content Block
        content_html:
    - label: Left Text Right Image
      icon: format_align_left
      value:
        _component_type: Left Text Right Image
        content_html:
        image:
        call_to_action:
          link_text:
          link_url:
    - label: Right Text Left Image
      icon: format_align_right
      value:
        _component_type: Right Text Left Image
        image:
        content_html:
        call_to_action:
          link_text:
          link_url:
    - label: CTA Link
      icon: touch_app
      value:
        _component_type: CTA Link
        text:
        url:


    - label: Group Items
      icon: view_module
      value:
        _component_type: Group Items
        heading:
        show_icons: false
        group_items:
          - title:
            description_html:
            svg_image:

        
